[package]
name = "fileflow-actions"
version = "0.1.0"
edition = "2024"

[dependencies]
fileflow-core = { path = "../fileflow-core" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

tempfile = "3"
